export const ActionTypes = {
  INCREMENT_COUNTER: "INCREMENT_COUNTER",
  DECREMENT_COUNTER: "DECREMENT_COUNTER",
  RESET_COUNTER: "RESET_COUNTER"
};

// export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
// export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
